baseurl = "/"
languageCode = "en-US"
title = "Alejandra Plazola"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/post/:year/:month/:day/:slug"

[params]
  avatar = "alee.jpeg"
  author = "Alejandra Plazola"
  occupation = "Biology student at the University of Texas at Austin"
  about = "My interests lie in all things about science, statistics, and education. In my free time, you can find me playing with my dogs, exercisng, and dancing."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "aplazola99"
  Email         = "aplazola48@gmail.com"
  Twitter       = "ale_plaz99"
  LinkedIn      = "alejandra-plazola"
  Instagram     = "ale_plaz99"


## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/post/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
